helm-ci:
    runs-on: ubuntu-latest
    needs: python-ci
    if: ${{ github.ref_name == 'Langrafka' }}
    steps:
      - name: Download helm artifacts
        uses: actions/download-artifact@v4
        with:
          name: helm-artifacts
          path: . 

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      # 1. Template Helm (ТЕПЕР ПЕРШИЙ КРОК)
      - name: Template Helm
        run: helm template ${{ env.HelmChartName }} ./helm-charts/${{ env.HelmChartName }} -f ./helm-charts/${{ env.HelmChartName }}/values.yaml # ВИПРАВЛЕНО ШЛЯХ

      # 2. Lint Helm (ТЕПЕР ДРУГИЙ КРОК)
      - name: Lint Helm
        run: helm lint ./helm-charts/${{ env.HelmChartName }} # ВИПРАВЛЕНО ШЛЯХ
        
      - name: Package Helm
        run: helm package ./helm-charts/${{ env.HelmChartName }}/ # ВИПРАВЛЕНО ШЛЯХ

      - name: Upload Helm package
        uses: actions/upload-artifact@v4
        with:
          name: helm-package
          path: ./*.tgz